project:
  type: website
  output-dir: docs

# render only the contents mentioned in the _quarto.yml file


website: 
  title: "AQMSP"
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Overview"
        path: "index.qmd"

      # - section: "Examples"
      #   contents:
      #     - examples/all_in_one.ipynb

execute:
  freeze: auto